version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: habit_postgres
    restart: always
    environment:
      POSTGRES_USER: habit
      POSTGRES_PASSWORD: habit
      POSTGRES_DB: habit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: habit_adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  postgres_data:
  redis_data: